### ISSUE TITLE
Python repubsub.Exchange('regex_demo', db='foobar') don't say if the connection is established

### ISSUE THREAD

**Issue by aj07mm** [rethinkdb/example-pubsub#6]
Its strange,
if i change the db to another name or something that dont exist the class don't throw errors, it just doesnt do a thing

```
def regex_publish():
    '''Publishes messages to a simple string topic'''

    exchange = repubsub.Exchange('regex_demo', db='altitude', host='localhost', port=28015)

    while True:
        topic = exchange.topic('logs')

        topic.publish({
            'id': 1
        })

        time.sleep(0.5)
```
in the code above the table exists and the record too but the publish dont work

**Comment by danielmewes** [comment]
@deontologician do you have an idea what might be wrong?

**Comment by deontologician** [comment]
Creating an exchange automatically creates a database and table. It's not possible to modify the 'id' field of a document in RethinkDB, so what's happening is it's failing to do an insert with a duplicate id. Our insert statement doesn't raise an exception however, when it fails, it only notifies you in the return value. It would look like this:

```json
{

    "deleted": 0 ,
    "errors": 1 ,
    "first_error": "Duplicate primary key `id`:
    {
    	"id":	1,
        "topic": "logs"
    }
    {
    	"id":	1,
        "topic": "logs"
    }" ,
    "inserted": 0 ,
    "replaced": 0 ,
    "skipped": 0 ,
    "unchanged": 0

}
```
This library doesn't check for that error, but probably should. In the meantime, you can avoid this by modifying the table to have a primary key other than `id` (create it beforehand, repubsub will only create a table if it doesn't already exist). Then you can use the key `id` without problems.

**Comment by deontologician** [comment]
I should stress that this library is just an example and it's source code is only about 150 lines. So feel free to copy and paste it into your code and modify it any way you need to.

**Comment by aj07mm** [comment]
Yeah @deontologician. I found the example very confusing. At the end, all you need to do is subscribe using change() and thats it. I don't know if you guys agree but i can do PR with a simpler example without the class, just the raw code to be easier to read and understand the concept.

**Comment by deontologician** [comment]
@aj07mm I agree, changefeeds by themselves are pretty easy to understand. This repo is mainly for people coming from using RabbitMQ or the like, and wondering how they could set up that same pattern with RethinkDB. If you're already using RethinkDB or don't need to adapt an existing infrastructure, this repo probably isn't for you.

Do you mind if I ask how you found this repo? Was it through the main site or googling?

**Comment by deontologician** [comment]
The reason I ask is because other people come here first when looking for "pubsub" for RethinkDB and I think the way we link to it from the main site may be adding too much emphasis to this use case, as if it's the best way to use changefeeds.

**Comment by aj07mm** [comment]
I was searching for some way to get live data from the database without the need to rerun queries all the time to fetch new data. I found the link here: http://rethinkdb.com/docs/publish-subscribe/python/
and also in google searches.

**Comment by deontologician** [comment]
@aj07mm Ok I opened an issue on our documentation tracker to make it harder for people to end up here when they are looking for changefeeds. Thanks for your input and sorry you got caught by this!

**Comment by aj07mm** [comment]
Nice! 
No problem. Im glad to help the project.
