### ISSUE TITLE
Documentation : Link not found

### ISSUE THREAD

**Issue by eon01** [rethinkdb/example-pubsub#8]
This link in the documentation  `https://github.com/rethinkdb/example-pubsub/blob/master/python/rethinkdb.com/docs/publish-subscribe/python` is a dead link.

**Comment by danielmewes** [comment]
Thanks for bringing this to our attention @eon01 . Where in the documentation did you find this link?

**Comment by eon01** [comment]
I found the dead link [here](https://github.com/rethinkdb/example-pubsub/tree/master/python) : `There is also an extensive description of how the library works and how to use it **here**.`

**Comment by danielmewes** [comment]
Thanks again. I updated the READMEs to use the correct URL.
